version: "3.7"

services:
   database:
       image: mysql:5.7
       container_name: database    
       environment:
           MYSQL_ROOT_HOST: '%'
           MYSQL_ROOT_PASSWORD: "[[root_password]]"
           MYSQL_DATABASE: "acrarium"
           MYSQL_USER: "acrarium"
           MYSQL_PASSWORD: "[[secure_password]]"
       expose:
           - "3306"
       volumes:
           - acrarium_data:/var/lib/mysql
       command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
   acrarium:
       image: f43nd1r/acrarium:latest
       container_name: acrarium
       depends_on:
           - database
       ports:
           - 8080:8080
       restart: on-failure
       environment:
           SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/acrarium?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
           SPRING_DATASOURCE_USERNAME: "acrarium"
           SPRING_DATASOURCE_PASSWORD: "[[secure_password]]"
           SPRING_JPA_DATABASEPLATFORM: org.hibernate.dialect.MySQL57Dialect
    
volumes:
   acrarium_data: 